/*
===========================================================================================
CREATE DATABASE AND SCHEMAS
===========================================================================================
SCRIPT PURPOSE:
THE BELOW SCRIPT CHECKS FOR THE EXISTENCE OF THE 'DATAWAREHOUSE' DATABASE. IF IT EXISTS, THE DATABASE IS DROPPED AND RECREATED.
THE SCRIPT ALSO SETS UP THREE SCHEMAS WITHIN THE DATABASE: BRONZE, SILVER AND GOLD

CAUTION:
RUNNING THIS SCRIPT WILL DROP THE ENTIRE 'DATABASE' IF THE DATABASE EXISTS.
ALL THE DATA IN THE DATABASE WILL BE DELETED PERMANENTLY. ENSURE YOU HAVE BACKUPS BEFORE RUNNING THIS SCRIPT.
  
/*
  

USE master;
GO

----DROP AND RECREATE THE 'DATABASE' DATABASE---
  IF EXISTS (SELECT 1 FROM SYS.DATABASE WHERE NAME = 'DATABASE')
  BEGIN
      ALTER DATABASE DATAWAHOUSE SET SINGLE_USER WITH ROLL_BACK IMMIDIATE;
      DROP DATABASE DATAWAREHOUSE;
  END;
  GO

***THE WORD GO IS USED AS A SEPARATOR***

---Create Database 'DataWarehouse'database 

Create Database DataWarehouse;

USE DataWarehouse;
GO

---CREATE SCHEMAS---

CREATE SCHEMA bronze;
GO
CREATE SCHEMA silver;
GO
CREATE SCHEMA gold;
GO
